spring:
  application:
   name: ai-code-helper
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-6b07eb5c899a4182bb70f8996a2cd208
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-6b07eb5c899a4182bb70f8996a2cd208
      streaming-chat-model:
        model-name: qwen-max
        api-key: sk-6b07eb5c899a4182bb70f8996a2cd208
bigmodel:
  api-key: d807938dcc56410c9f9dba6e961f943f.M9NIiclum7zyf9cN